TimeTracker/TimeTracker/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TimeTracker_Repository;

namespace TimeTracker.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        public async Task<IActionResult> Index()
        {
            return View();
        }
    }
}

TimeTracker/TimeTracker/Controllers/LeaveController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using TimeTracker.Helper;
using TimeTracker.Models;
using TimeTracker.Models.Leave;
using TimeTracker_Data.Model;
using TimeTracker_Model;
using TimeTracker_Model.Leave;
using TimeTracker_Repository.LeaveRepo;
using TimeTracker_Repository.UserRepo;

namespace TimeTracker.Controllers
{
    [Authorize]
    public class LeaveController : Controller
    {
        #region Declaration
        private readonly ILeaveRepo _leaveRepo;
        private readonly IMapper _mapper;
        private readonly IUserRepo _userRepo;
        private readonly IHttpContextAccessor _httpContextAccessor;
        #endregion

        #region Const
        public LeaveController(ILeaveRepo leaveRepo, IMapper mapper, IUserRepo userRepo, IHttpContextAccessor httpContextAccessor)
        {
            _leaveRepo = leaveRepo;
            _mapper = mapper;
            _userRepo = userRepo;
            _httpContextAccessor = httpContextAccessor;
        }
        #endregion

        #region Method
        public async Task<IActionResult> Index()
        {
            var users = await _userRepo.GetUserLookup();
            ViewBag.Users = new SelectList(users, "Id", "Username");
            return View();
        }

        public async Task<IActionResult> LoadLeave(DatatableParamViewModel param, string filter)
        {
            var dtParam = _mapper.Map<LeaveFilterModel>(param);

            int userId = _httpContextAccessor?.HttpContext?.User.GetIdFromClaim() ?? 0;
            dtParam.UserId = userId;

            if (!string.IsNullOrWhiteSpace(filter) && filter != "{}")
            {
                var filterData = JsonConvert.DeserializeObject<LeaveFilterModel>(filter);
                dtParam.UserId = filterData?.UserId == null || filterData?.UserId == 0 ? userId : filterData?.UserId;
            }

            var leaveList = await _leaveRepo.GetLeave(dtParam);
            var lst = _mapper.Map<List<LeaveListViewModel>>(leaveList);

            return Json(new
            {
                param.sEcho,
                iTotalRecords = 0,
                iTotalDisplayRecords = 0,
                aaData = lst
            });
        }

        public async Task<IActionResult> DisplayLeaveCount(int userId)
        {
            userId = (userId > 0 ? userId : _httpContextAccessor?.HttpContext?.User.GetIdFromClaim()) ?? 0;

            var startFinancialYearDate
                = new DateTime(DateTime.Now.Month > 3 ? DateTime.Now.Year : DateTime.Now.Year - 1, 4, 1);
            var endFinancialYearDate
                = new DateTime(DateTime.Now.Month < 4 ? DateTime.Now.Year : DateTime.Now.Year - 1, 3, 31);

            var usedLeaveCount = await _leaveRepo.LeaveCount(
                userId, startFinancialYearDate, endFinancialYearDate);

            // Joining date after probation period.
            var joiningDate = await _userRepo.GetJoiningDate(userId);

            int totalLeave = (12 * (endFinancialYearDate.Year - joiningDate.Year) + (endFinancialYearDate.Month - joiningDate.Month)) + 1;

            totalLeave = totalLeave > 12 ? 12 : totalLeave;

            var pendingLeaveCount = totalLeave - usedLeaveCount < 0 ? 0 : totalLeave - usedLeaveCount;

            return Json(new { totalLeave, pendingLeaveCount });
        }

        public async Task<IActionResult> Create()
        {
            int userId = _httpContextAccessor?.HttpContext?.User.GetIdFromClaim() ?? 0;
            var users = await _userRepo.GetUserLookup();
            var currentUser = users.Where(a => a.Id == userId);
            int roleId = User.GetLoginRole();
            if (roleId == (int)TimeTracker_Model.Roles.Admin)
            {
                ViewBag.Users = new SelectList(users, "Id", "Username");
            }
            else
            {
                ViewBag.Users = new SelectList(currentUser, "Id", "Username");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddLeaveViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int userId = _httpContextAccessor?.HttpContext?.User.GetIdFromClaim() ?? 0;
                    int roleId = User.GetLoginRole();
                    if (roleId != (int)TimeTracker_Model.Roles.Admin)
                    {
                        model.UserId = userId;
                    }

                    var startFinancialYearDate
                        = new DateTime(DateTime.Now.Month > 3 ? DateTime.Now.Year : DateTime.Now.Year - 1, 4, 1);

                    var endFinancialYearDate
                        = new DateTime(DateTime.Now.Month < 4 ? DateTime.Now.Year : DateTime.Now.Year - 1, 3, 31);

                    var leaveCount = await _leaveRepo.LeaveCount(
                        model.UserId, startFinancialYearDate, endFinancialYearDate);

                    var addLeave = _mapper.Map<AddLeaveModel>(model);

                    // Joining date after probation period.
                    var joiningDate = await _userRepo.GetJoiningDate(userId);

                    int totalLeave = (12 * (endFinancialYearDate.Year - joiningDate.Year) + (endFinancialYearDate.Month - joiningDate.Month)) + 1;

                    totalLeave = totalLeave > 12 ? 12 : totalLeave;

                    addLeave.IsPaid = leaveCount < totalLeave;
                    var result = await _leaveRepo.AddLeave(addLeave);

                    if (result)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> ChangeStatus(int id, int btnId)
        {
            bool isSuccess = false;
            string message = "";
            try
            {
                if (id > 0)
                {
                    isSuccess = await _leaveRepo.ChangeStatus(id, btnId);
                    message = isSuccess ? AppMessages.SAVE_SUCCESS : AppMessages.SOMETHING_WRONG;
                }
            }
            catch (Exception)
            {
                throw;
                //LogWriter.LogWrite(ex.Message, MessageTypes.Error);
            }
            return Json(new { isSuccess, message });
        }

        public async Task<IActionResult> GetLeaveDetail(int id)
        {
            try
            {
                var leaveDetail = new List<LeaveListViewModel>();
                if (id > 0)
                {
                    var result = await _leaveRepo.GetLeaveDetail(id);
                    leaveDetail = _mapper.Map<List<LeaveListViewModel>>(result);
                }
                return PartialView("_LeaveDetail", leaveDetail);
            }
            catch (Exception)
            {
                throw;
            }
        }
        #endregion
    }
}

TimeTracker/TimeTracker/Controllers/UserController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Diagnostics;
using System.Net;
using TimeTracker.Configurations;
using TimeTracker.Helper;
using TimeTracker.Models;
using TimeTracker.Models.User;
using TimeTracker_Data.Model;
using TimeTracker_Model;
using TimeTracker_Model.User;
using TimeTracker_Repository.AWSRepo;
using TimeTracker_Repository.UserRepo;

namespace TimeTracker.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserRepo _userRepo;
        private readonly IMapper _mapper;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IAWSS3BucketService _awsS3BucketService;

        public UserController(IUserRepo userRepo,
                              IMapper mapper,
                              IHttpContextAccessor httpContextAccessor,
                              IOptions<AwsConfiguration> awsConfiguration)
        {
            _userRepo = userRepo;
            _mapper = mapper;
            _httpContextAccessor = httpContextAccessor;
            _awsS3BucketService = new AWSS3BucketService(awsConfiguration.Value);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> LoadUser(DatatableParamViewModel param)
        {
            var dtParam = _mapper.Map<UserFilterModel>(param);

            var (userList, totalRecord) = await _userRepo.GetUserList(dtParam);

            return Json(new
            {
                param.sEcho,
                iTotalRecords = totalRecord,
                iTotalDisplayRecords = totalRecord,
                aaData = userList
            });
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(AddUserViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.Url = await _awsS3BucketService.UploadFile(model.AvatarFile);
                    var addUser = _mapper.Map<AddEditUserModel>(model);
                    var result = await _userRepo.AddUser(addUser);

                    if (result)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }
            return View();
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Update(int id)
        {
            var user = await _userRepo.GetUserById(id);
            var model = _mapper.Map<EditUserViewModel>(user);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(EditUserViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    model.Url = await _awsS3BucketService.UploadFile(
                        model.AvatarFile, model.Url ?? "");

                    var editUser = _mapper.Map<AddEditUserModel>(model);
                    editUser.RoleId = _httpContextAccessor?.HttpContext?.User?.GetLoginRole() ?? 0;

                    var result = await _userRepo.UpdateUser(editUser);
                    if (result)
                    {
                        if (model.FromProfile)
                        { return RedirectToAction("UserProfile"); }
                        else
                        { return RedirectToAction("Index"); }
                    }
                }
                if (model.FromProfile)
                { return View("UserProfile"); }
                else
                { return View(); }
            }
            catch (Exception)
            {
                throw;
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> DeleteUser(int id)
        {
            bool isSuccess = false;
            string message = "";
            try
            {
                if (id > 0)
                {
                    isSuccess = await _userRepo.DeleteUser(id);
                    message = isSuccess ? AppMessages.DELETE_SUCCESS : AppMessages.SOMETHING_WRONG;
                }
            }
            catch (Exception ex)
            {
                //LogWriter.LogWrite(ex.Message, MessageTypes.Error);
            }
            return Json(new { isSuccess, message });
        }

        public async Task<IActionResult> UserProfile()
        {
            int? userId = _httpContextAccessor?.HttpContext?.User.GetIdFromClaim();
            var user = await _userRepo.GetUserById(userId ?? 0);
            var pic = user.Url;
            var model = _mapper.Map<EditUserViewModel>(user);
            return View(model);
        }

        public async Task<IActionResult> DeleteProfilePic(int id, string url)
        {
            bool isSuccess = false;
            string message = "";
            try
            {
                if (id > 0)
                {
                    await _awsS3BucketService.DeleteFile(url);
                    isSuccess = await _userRepo.DeleteProfilePic(id);
                    message = isSuccess ? AppMessages.DELETE_SUCCESS : AppMessages.SOMETHING_WRONG;
                }
            }
            catch (Exception ex)
            {
                LogWriter.LogWrite(ex);
            }
            return Json(new { isSuccess, message });
        }

        [HttpGet]
        public async Task<IActionResult> GetProfilePic()
        {
            string url = "";
            try
            {
                int? userId = _httpContextAccessor?.HttpContext?
                    .User.GetIdFromClaim();
                var user = await _userRepo.GetUserById(userId ?? 0);
                url = user?.Url ?? "";
            }
            catch { }
            return Json(url);
        }

        public async Task<IActionResult> ValidateEmail(string Email, int Id = 0)
        {
            return Json(await _userRepo.ValidateEmail(Email, Id));
        }

        public async Task<IActionResult> ValidateContactNo(string ContactNo, int Id = 0)
        {
            return Json(await _userRepo.ValidateContactNo(ContactNo, Id));
        }

        //public async Task<IActionResult> CheckUpdate()
        //{
        //    bool isSuccess = false;
        //    string message = "Something went wrong!";
        //    try
        //    {
        //        try
        //        {
        //            await Task.Run(() =>
        //            {
        //                string stopDelete = Path.Combine(_hostingEnvironment.WebRootPath, @"TimeTrackerService\Stop.bat");
        //                Process proc = new Process();
        //                proc.StartInfo.FileName = stopDelete;
        //                proc.StartInfo.UseShellExecute = true;
        //                proc.StartInfo.Verb = "runas";
        //                proc.Start();
        //            });
        //        }
        //        catch { }

        //        try
        //        {
        //            await Task.Run(() =>
        //            {
        //                string stopDelete = Path.Combine(_hostingEnvironment.WebRootPath, @"TimeTrackerService\Delete.bat");
        //                Process proc = new Process();
        //                proc.StartInfo.FileName = stopDelete;
        //                proc.StartInfo.UseShellExecute = true;
        //                proc.StartInfo.Verb = "runas";
        //                proc.Start();
        //            });
        //        }
        //        catch { }

        //        await Task.Run(() =>
        //        {
        //            DirectoryInfo directoryInfo = new DirectoryInfo(@"C:\TimeTrackerService\");
        //            foreach (FileInfo file in directoryInfo.GetFiles())
        //            {
        //                file.Delete();
        //            }
        //        });

        //        await Task.Run(() =>
        //        {
        //            string fileName = Path.Combine(_hostingEnvironment.WebRootPath, "TimeTrackerService/");
        //            WebClient webClient = new WebClient();
        //            {
        //                webClient.DownloadFile(fileName + @"\TimeTrackerService.exe", @"C:\TimeTrackerService\TimeTrackerService.exe");
        //                webClient.DownloadFile(fileName + @"\Newtonsoft.Json.dll", @"C:\TimeTrackerService\Newtonsoft.Json.dll");
        //            }
        //        });

        //        await Task.Run(() =>
        //        {
        //            string installStart = Path.Combine(_hostingEnvironment.WebRootPath, @"TimeTrackerService\Install_Start.bat");
        //            Process proc1 = new Process();
        //            proc1.StartInfo.FileName = installStart;
        //            proc1.StartInfo.UseShellExecute = true;
        //            proc1.StartInfo.Verb = "runas";
        //            proc1.Start();
        //        });

        //        isSuccess = true;
        //        message = "Time Tracker has been updated.";
        //    }
        //    catch { }
        //    return Json(new { isSuccess, message });
        //}
    }
}

TimeTracker/TimeTracker/Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TimeTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TimeTracker.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TimeTracker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TimeTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TimeTracker/TimeTracker/Views/Shared/_MainMenu.cshtml
@using TimeTracker.Helper;
@using TimeTracker_Model
@{
    int roleId = 0;
    if (User != null)
    {
        roleId = User.GetLoginRole();
    }
}

<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
    <!-- Add icons to the links using the .nav-icon class
         with font-awesome or any other icon font library -->
    <li class="nav-item menu-open">
        <a asp-action="Index" asp-controller="Dashboard" class="nav-link" id="menuDashboard">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>Dashboard</p>
        </a>
    </li>
    <li class="nav-item">
        <a href="#" class="nav-link" id="menuMaster">
            <i class="nav-icon fas fa-th"></i>
            <p>
                Masters
                <i class="fas fa-angle-left right"></i>
            </p>
        </a>
        <ul class="nav nav-treeview">
            @if (roleId == (int)Roles.Admin)
            {
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="User" class="nav-link" id="menuUsers">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Users</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Setting" asp-action="Index" class="nav-link" id="menuSettings">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Settings</p>
                    </a>
                </li>
            }
            <li class="nav-item">
                <a asp-controller="Holiday" asp-action="Index" class="nav-link" id="menuHolidayList">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Holiday List</p>
                </a>
            </li>
            @if (roleId == (int)Roles.Admin || roleId == (int)Roles.HR)
            {
                <li class="nav-item">
                    <a asp-controller="Resource" asp-action="Index" class="nav-link" id="menuResource">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Resources</p>
                    </a>
                </li>
            }
            <li class="nav-item">
                <a asp-controller="Leave" asp-action="Index" class="nav-link" id="menuLeaveList">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Leave</p>
                </a>
            </li>
            @if (roleId == (int)Roles.Admin)
            {
                <li class="nav-item">
                    <a asp-controller="UpdateService" asp-action="Index" class="nav-link" id="menuUpdateService">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Update Service</p>
                </a>
            </li>
            }
        </ul>
    </li>
    @*<li class="nav-item">
        <a href="#" class="nav-link" id="menuAttendance">
            <i class="nav-icon fa-regular fa-calendar-check"></i>
            <p>
                Attendance
                <i class="fas fa-angle-left right"></i>
            </p>
        </a>
        <ul class="nav nav-treeview">
            <li class="nav-item">
                <a asp-controller="SystemLog" asp-action="Index" class="nav-link" id="menuSystemLog">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Daily Report</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="SystemLog" asp-action="MonthlyReport" class="nav-link" id="menuMonthlyReport">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Monthly Report</p>
                </a>
            </li>
        </ul>
    </li>*@

    <li class="nav-item">
        <a href="#" class="nav-link" id="menuMainSalary">
            <i class="nav-icon fa-solid fa-wallet"></i>
            <p>
                Salary
                <i class="fas fa-angle-left right"></i>
            </p>
        </a>
        <ul class="nav nav-treeview">
            <li class="nav-item">
                <a asp-controller="Salary" asp-action="Index" class="nav-link" id="menuSalary">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Salary</p>
                </a>
            </li>
            <li class="nav-item">
                <a asp-controller="Salary" asp-action="SalaryReport" class="nav-link" id="menuSalaryReport">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Salary Report</p>
                </a>
            </li>
        </ul>
    </li>
</ul>