TimeTracker/TimeTracker/Models/Resource/FollowupListViewModel.cs
namespace TimeTracker.Models.Resource
{
    public class FollowupListViewModel
    {
        public DateTime DateTime { get; set; }
        public string Remarks { get; set; }
    }
}

TimeTracker/TimeTracker/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TimeTracker_Repository;

namespace TimeTracker.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        public async Task<IActionResult> Index()
        {
            return View();
        }
    }
}

TimeTracker/TimeTracker/Controllers/ResourceController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestSharp;
using System.Net.Http.Headers;
using TimeTracker.Models;
using TimeTracker.Models.Resource;
using TimeTracker_Model;
using TimeTracker_Model.Resources;
using TimeTracker_Repository.ResourcesRepo;

namespace TimeTracker.Controllers
{
    [Authorize(Roles = "Admin,HR")]
    public class ResourceController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IResourceRepo _resourcesRepo;

        public ResourceController(IMapper mapper, IResourceRepo resourcesRepo)
        {
            _mapper = mapper;
            _resourcesRepo = resourcesRepo;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult AddResource()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> AddResource(ResourceViewModel model)
        {
            await ListOfResources(model);
            return RedirectToAction("AddResource");
        }

        private async Task ListOfResources(ResourceViewModel model)
        {
            for (int i = 0; i < i + 1; i++)
            {
                string url = $"https://prod.hirect.ai/hirect/candidate-service/candidates/search?searchDirect=true&cityId={model.CityId}&qs={model.Designation}&pageNum={i}&pageSize=20";
                var client = new RestClient(url);
                client.Timeout = -1;
                client.FollowRedirects = false;
                var request = new RestRequest(Method.POST);
                request.AddHeader("authority", "prod.hirect.ai");
                request.AddHeader("accept", "application/json, text/plain, */*");
                request.AddHeader("accept-language", "en-US,en;q=0.9");
                request.AddHeader("content-type", "application/json;charset=UTF-8 application/json;charset=UTF-8");
                request.AddHeader("origin", "https://recruiter.hirect.in");
                request.AddHeader("referer", "https://recruiter.hirect.in/");
                request.AddHeader("region", "in");
                request.AddHeader("sec-ch-ua", "\"Google Chrome\";v=\"107\", \"Chromium\";v=\"107\", \"Not=A?Brand\";v=\"24\"");
                request.AddHeader("sec-ch-ua-mobile", "?0");
                request.AddHeader("sec-ch-ua-platform", "\"Windows\"");
                request.AddHeader("sec-fetch-dest", "empty");
                request.AddHeader("sec-fetch-mode", "cors");
                request.AddHeader("sec-fetch-site", "cross-site");
                client.UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36";
                request.AddHeader("x-appversion", "2.1.0");
                request.AddHeader("x-brand", "Windows");
                request.AddHeader("x-deviceid", "6ae23cc7-1fe0-4830-946a-41f90b0b87e4");
                request.AddHeader("x-idtoken", $"{model.Token}");
                request.AddHeader("x-model", "10");
                request.AddHeader("x-os", "webapp");
                request.AddHeader("x-region", "in");
                request.AddHeader("x-role", "1");
                request.AddHeader("x-timestamp", "1669877252654");
                request.AddHeader("x-uid", "eb02f4980a8546a2ad91f23e5398");

                string[] education = model.education.Split(',');
                string[] experience = model.experience.Split(',');
                string[] salary = model.salary.Split(',');
                var content = JsonContent.Create(new
                {
                    education = education,
                    experience = experience,
                    salary = salary,
                    gender = 0,
                    minAge = 18,
                });

                var body = JsonConvert.SerializeObject(content.Value);
                request.AddParameter("application/json;charset=UTF-8 application/json;charset=UTF-8", body, ParameterType.RequestBody);
                IRestResponse response = client.Execute(request);

                if (response.IsSuccessful)
                {
                    var deserializeObject = JsonConvert.DeserializeObject<dynamic>(response.Content);
                    var list = deserializeObject["data"]["list"];

                    if (((Newtonsoft.Json.Linq.JArray)list).Count == 0)
                    { break; }

                    foreach (var item in list)
                    {
                        string id = item["id"];
                        string preferenceId = item["preferenceId"];

                        var resource = await _resourcesRepo.GetResourceById(id);
                        if (string.IsNullOrWhiteSpace(resource.id))
                        {
                            await GetResourceDetails(id, preferenceId, model.Token);
                        }
                    }
                }
            }
        }

        //private async Task ListOfResources(ResourceViewModel model)
        //{
        //    for (int i = 0; i < i + 1; i++)
        //    {
        //        //string url = $"https://prod.hirect.ai/hirect/candidate-service/candidates/search?searchDirect=true&cityId={model.CityId}&qs={model.Designation}&pageNum={i}&pageSize=20";
        //        string url = "https://prod.hirect.ai/hirect/candidate-service/candidates/search?searchDirect=true&cityId=356&qs=Flutter&pageNum=0&pageSize=20";

        //        HttpClient _httpClient = new HttpClient();
        //        _httpClient.BaseAddress = new Uri(url);
        //        _httpClient.DefaultRequestHeaders.Accept.Clear();
        //        _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

        //        _httpClient.DefaultRequestHeaders.Add("authority", "prod.hirect.ai");
        //        _httpClient.DefaultRequestHeaders.Add("accept", "application/json, text/plain, */*");
        //        _httpClient.DefaultRequestHeaders.Add("accept-language", "en-US,en;q=0.9");
        //        _httpClient.DefaultRequestHeaders.Add("origin", "https://recruiter.hirect.in");
        //        _httpClient.DefaultRequestHeaders.Add("referer", "https://recruiter.hirect.in/");
        //        _httpClient.DefaultRequestHeaders.Add("region", "in");
        //        _httpClient.DefaultRequestHeaders.Add("sec-ch-ua", "\"Google Chrome\";v=\"107\", \"Chromium\";v=\"107\", \"Not=A?Brand\";v=\"24\"");
        //        _httpClient.DefaultRequestHeaders.Add("sec-ch-ua-mobile", "?0");
        //        _httpClient.DefaultRequestHeaders.Add("sec-ch-ua-platform", "\"Windows\"");
        //        _httpClient.DefaultRequestHeaders.Add("sec-fetch-dest", "empty");
        //        _httpClient.DefaultRequestHeaders.Add("sec-fetch-mode", "cors");
        //        _httpClient.DefaultRequestHeaders.Add("sec-fetch-site", "cross-site");
        //        _httpClient.DefaultRequestHeaders.Add("x-appversion", "2.1.0");
        //        _httpClient.DefaultRequestHeaders.Add("x-brand", "Windows");
        //        _httpClient.DefaultRequestHeaders.Add("x-deviceid", "792de51e4d5be52a35f55f3570193fc3"); //Change
        //        _httpClient.DefaultRequestHeaders.Add("x-idtoken", $"{model.Token}");
        //        _httpClient.DefaultRequestHeaders.Add("x-model", "10");
        //        _httpClient.DefaultRequestHeaders.Add("x-os", "webapp");
        //        _httpClient.DefaultRequestHeaders.Add("x-region", "in");
        //        _httpClient.DefaultRequestHeaders.Add("x-role", "1");
        //        _httpClient.DefaultRequestHeaders.Add("x-timestamp", "1669877252654"); //Change
        //        _httpClient.DefaultRequestHeaders.Add("x-uid", "eb02f4980a8546a2ad91f23e5398");

        //        string[] education = model.education.Split(',');
        //        string[] experience = model.experience.Split(',');
        //        string[] salary = model.salary.Split(',');
        //        var content = JsonContent.Create(new
        //        {
        //            education = education,
        //            experience = experience,
        //            salary = salary,
        //            gender = 0,
        //            minAge = 18,
        //        });

        //        var response = await _httpClient.PostAsync("", content);

        //        if (response.IsSuccessStatusCode)
        //        {
        //            var result = response.Content.ReadAsStringAsync().Result;

        //            var deserializeObject = JsonConvert.DeserializeObject<dynamic>(result);
        //            var list = deserializeObject["data"]["list"];

        //            if (((Newtonsoft.Json.Linq.JArray)list).Count == 0)
        //            { break; }

        //            foreach (var item in list)
        //            {
        //                string id = item["id"];
        //                string preferenceId = item["preferenceId"];

        //                var resource = await _resourcesRepo.GetResourceById(id);
        //                if (string.IsNullOrWhiteSpace(resource.id))
        //                {
        //                    await GetResourceDetails(id, preferenceId, model.Token);
        //                }
        //            }
        //        }
        //    }
        //}

        //private async Task ListOfResources(ResourceViewModel model)
        //{
        //    var deserializeObject = JsonConvert.DeserializeObject<dynamic>(model.Details);
        //    var list = deserializeObject["data"]["list"];

        //    foreach (var item in list)
        //    {
        //        string id = item["id"];
        //        string preferenceId = item["preferenceId"];

        //        var resource = await _resourcesRepo.GetResourceById(id);
        //        if (string.IsNullOrWhiteSpace(resource.id))

TimeTracker/TimeTracker/Views/Resource/AddResource.cshtml
@model TimeTracker.Models.Resource.ResourceViewModel
@{
    ViewData["Title"] = "Add Resource";
}

@section ContentHeader{
    <div class="col-sm-6">
        <h4 class="m-0">Resources</h4>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Dashboard">Dashboard</a></li>
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Resource">Resources</a></li>
            <li class="breadcrumb-item active">Add Resource</li>
        </ol>
    </div>
}

<div class="row">
    <div class="col-md-12">
        <div class="card card-lightblue card-outline">
            <div class="card-header">
                <h3 class="card-title font-color">
                    <i class="fa-solid fa-user-plus"></i>
                    Add Resource
                </h3>
            </div>
            <form asp-action="AddResource">
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-md-4">
                            <label asp-for="Designation" class="required">Designation</label>
                            <select class="form-control form-control-sm" asp-for="Designation">
                                <option value="NET Developer">NET Developer</option>
                                <option value="Flutter">Flutter</option>
                                <option value="Android Engineer">Android Engineer</option>
                                <option value="Android App Designer">Android App Designer</option>
                                <option value="React JS">React JS</option>
                                <option value="React Native">React Native</option>
                                <option value="Node JS Engineer">Node JS Engineer</option>
                                <option value="Business Development Executive">Business Development Executive</option>
                                <option value="UI/UX Designer">UI/UX Designer</option>
                                <option value="UI/UX Developer">UI/UX Developer</option>
                                <option value="UX Designer">UX Designer</option>
                                <option value="UI Designer">UI Designer</option>
                                <option value="Human Resources Consultant">Human Resources Consultant</option>
                                <option value="Human Resource (HR) Manager">Human Resource (HR) Manager</option>
                                <option value="Employee Relations Manager">Employee Relations Manager</option>
                                <option value="Xamarin">Xamarin</option>
                                <option value="Director of Human Resource">Director of Human Resource</option>
                            </select>
                        </div>
                        <div class="form-group col-md-4">
                            <label asp-for="education" class="required">Education</label>
                            <input asp-for="education" type="text" class="form-control form-control-sm" value="1,2">
                        </div>
                        <div class="form-group col-md-4">
                            <label asp-for="experience" class="required">Experience (1=Any | 2=Fresher | 3=0-1 Year | 4=1-3 Years | 5=3-5 Years | 6=5-10 Years | 7=10+ Years)</label>
                            <input asp-for="experience" type="text" class="form-control form-control-sm" value="1">
                        </div>
                        <div class="form-group col-md-4">
                            <label asp-for="salary" class="required">Salary</label>
                            <input asp-for="salary" type="text" class="form-control form-control-sm" value="1">
                        </div>
                        <div class="form-group col-md-4">
                            <label asp-for="CityId" class="required">City Id</label>
                            <input asp-for="CityId" type="text" class="form-control form-control-sm" value="356">
                        </div>
                        <div class="form-group col-md-12">
                            <label asp-for="Token" class="required">Token</label>
                            <input asp-for="Token" type="text" class="form-control form-control-sm" onblur="setToken()">
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <input type="submit" class="btn btn-info theme-color" value="Submit" />
                    <button type="reset" class="btn btn-secondary ml-1">Reset</button>
                </div>
            </form>
        </div>
    </div>
</div>



@section Scripts{
    <script>
        $(document).ready(function () {
            SelectedMenu('menuMaster', 'menuResource');
            $('#Token').val(localStorage.getItem('WCT_Token'));


            var settings = {
                "url": "https://prod.hirect.ai/hirect/candidate-service/candidates/search?searchDirect=true&cityId=275&qs=.NET Developer&pageNum=0&pageSize=10",
                "method": "POST",
                "timeout": 0,
                "headers": {
                    "authority": "prod.hirect.ai",
                    "accept": "application/json, text/plain, */*",
                    "accept-language": "en-US,en;q=0.9",
                    "content-type": "application/json;charset=UTF-8 application/json;charset=UTF-8",
                    "origin": "https://recruiter.hirect.in",
                    "referer": "https://recruiter.hirect.in/",
                    "region": "in",
                    "sec-ch-ua": "\"Google Chrome\";v=\"107\", \"Chromium\";v=\"107\", \"Not=A?Brand\";v=\"24\"",
                    "sec-ch-ua-mobile": "?0",
                    "sec-ch-ua-platform": "\"Windows\"",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "cross-site",
                    //"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
                    "x-appversion": "2.1.0",
                    "x-brand": "Windows",
                    "x-deviceid": "792de51e4d5be52a35f55f3570193fc3",
                    "x-idtoken": "eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiZWIwMmY0OTgwYTg1NDZhMmFkOTFmMjNlNTM5OCIsImNyZWF0ZVRpbWUiOjE2NzMyNDEzNTEzNDQsImlhdCI6MTY3MzI0MTM1MSwiaXNzIjoiaGlyZWN0X2FwcF9pc3N1ZXIifQ.RkD5AS4cn6tys5SZE5tTU5xnPL6-_tuJ5xnEH6CJYw0",
                    "x-model": "10",
                    "x-os": "webapp",
                    "x-region": "in",
                    "x-role": "1",
                    "x-timestamp": "1669877252654",
                    "x-uid": "eb02f4980a8546a2ad91f23e5398"
                },
                "data": "{\"education\":[\"2\",\"3\"],\"experience\":[\"1\"],\"salary\":[\"1\"],\"gender\":0,\"minAge\":18}",
            };

            $.ajax(settings).done(function (response) {
                console.log(response);
            });
        });

        function setToken() {
            localStorage.setItem('WCT_Token', $('#Token').val());
        }
    </script>
}

TimeTracker/TimeTracker/Views/Resource/Index.cshtml
@using TimeTracker.Helper
@using TimeTracker_Model
@model TimeTracker.Models.Resource.FollowupAddViewModel

@{
    ViewData["Title"] = "Resources";

    int roleId = 0;
    if (User != null)
    {
        roleId = User.GetLoginRole();
    }
}

@section ContentHeader{
    <div class="col-sm-6">
        <h4 class="m-0">Resources</h4>
    </div>
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a asp-action="Index" asp-controller="Dashboard">Dashboard</a></li>
            <li class="breadcrumb-item active">Resources</li>
        </ol>
    </div>
}

<div class="row">
    <div class="col-md-12">
        <div class="card card-lightblue card-outline">
            <div class="card-header">
                <h3 class="card-title font-color">
                    <i class="fa-solid fa-calendar-days"></i>
                    Resources
                </h3>
                <div style="float:right; display:flex;">
                    <div style="float:right;width: 160px;">
                        <select class="form-control form-control-sm" asp-items="Html.GetEnumSelectList<ResourceStatus>()" id="cmbStatus">
                            <option value="">Select Status</option>
                        </select>
                    </div>
                    <div style="float:right;width: 130px;margin-left:5px;">
                        <input type="text" class="form-control form-control-sm" placeholder="Designation" id="cmbDesignation" />
                    </div>
                    <div style="float:right; margin-left:5px;width: 100px;">
                        <input type="text" class="form-control form-control-sm" placeholder="City" id="cmbCity" />
                    </div>
                    <div style="float:right; margin-left:5px;">
                        <select class="form-control select2bs4 select2-multi-update" multiple="multiple" data-placeholder="Hide Columns" style="width: 180px;" id="cmdColumn">
                            <option value="0">Name</option>
                            <option value="1">Gender</option>
                            <option value="2">Mobile</option>
                            <option value="3">Email</option>
                            <option value="4">Work Years</option>
                            <option value="5">Designation</option>
                            <option value="6">Status</option>
                            <option value="7">Degree</option>
                            <option value="8">DOB</option>
                            <option value="9">City</option>
                            <option value="10">Work Start Date</option>
                            <option value="11">PreferenceId</option>
                        </select>
                    </div>

                    <div style="float:right;margin-left:5px;">
                        <select class="form-control form-control-sm" id="cmbExperience">
                            <option value="-1">All</option>
                            <option value="0">Freshers</option>
                            @{
                                for (int i = 1; i <= 10; i++)
                                {
                                    <option value="@i">@i-Years</option>
                                }
                            }
                        </select>
                    </div>

                    @if (roleId == (int)Roles.Admin)
                    {
                        <div style="float:right; margin-left:5px;">
                            <a asp-action="AddResource" class="btn btn-block btn-info btn-sm theme-color">Create</a>
                        </div>
                    }
                </div>

            </div>
            <div class="card-body">
                <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-sm table-bordered table-striped" id="tblResource">
                                <thead>
                                    <tr>
                                        <th style="min-width: 120px">Name</th>
                                        <th style="min-width: 70px">Gender</th>
                                        <th style="min-width: 65px">Mobile</th>
                                        <th style="min-width: 120px">Email</th>
                                        <th style="min-width: 85px">Experience</th>
                                        <th style="min-width: 120px">Designation</th>
                                        <th style="min-width: 110px">Status</th>
                                        <th style="min-width: 70px">Degree</th>
                                        <th style="min-width: 80px">Birth Date</th>
                                        <th style="min-width: 100px">City</th>
                                        <th style="min-width: 120px">Work Start Date</th>
                                        @*<th style="min-width: 150px">Comp. Exp.</th>*@
                                        <th style="min-width: 120px">Preference Id</th>
                                        <th style="min-width: 120px">Created on</th>
                                        <th style="min-width: 90px">Follow-up</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalFollowup">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Take a follow-up</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="frmFollowup">
                <div class="modal-body">
                    <input type="hidden" asp-for="PreferenceId" id="hdnPreferenceId" />
                    <div class="row mt-1">
                        <div class="form-group col-md-12">
                            <label asp-for="Remarks">Remarks</label>
                            <textarea asp-for="Remarks" class="form-control" rows="2"></textarea>
                            <span asp-validation-for="Remarks" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            <label asp-for="DateTime">Date Time</label>
                            <input asp-for="DateTime" type="datetime-local" class="form-control form-control-sm">
                            <span asp-validation-for="DateTime" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-6">
                            <label asp-for="ResourceStatus">Status</label>
                            <select asp-for="ResourceStatus" class="form-control form-control-sm" asp-items="Html.GetEnumSelectList<ResourceStatus>()">
                                <option value="">Select Status</option>
                            </select>
                            <span asp-validation-for="ResourceStatus" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="modal-footer justify-content-end">
                    <button type="submit" class="btn btn-info btn-sm theme-color">Add Follow-up</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="modalFollowupList">
    <div class="modal-dialog" style="max-width: 600px;">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Follow-up List</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="loadFollowup">
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/js/resources.js"></script>

    <script>
        $(document).ready(function () {
            SelectedMenu('menuMaster', 'menuResource');
            bindDataTable();
        });
    </script>
}

TimeTracker/TimeTracker/Views/Resource/_FollowupList.cshtml
@model List<TimeTracker.Models.Resource.FollowupListViewModel>

<table class="table table-sm table-bordered table-striped">
    <thead>
        <tr>
            <th style="width: 113px;">Followup Date</th>
            <th>Remarks</th>
        </tr>
    </thead>
    <tbody>
        @if (Model is { Count: > 0 })
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>@item.DateTime.ToString("dd, MMM-yyyy")</td>
                    <td>@item.Remarks</td>
                </tr>
            }
        }
    </tbody>
</table>